objects/Job_Applicant__c.object
<CustomObject>
    <description>Job Applicant</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hyderabad</fullName>
                </value>
                <value>
                    <fullName>Banglore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_No__c</fullName>
        <label>Job No</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Applicants</relationshipLabel>
        <relationshipName>Job_Applicants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Interviewing</fullName>
                </value>
                <value>
                    <fullName>Selected</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Applicant</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Job Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/jobapplicant.cls
public class jobapplicant {
    public job_applicant__c jobapp{get;set;}
    public  id jobid{get;set;}
    public jobapplicant(ApexPages.StandardController controller) {
     jobapp = (job_applicant__c) controller.getrecord();
     jobapp.job_no__c =(id) System.currentPageReference().getParameters().get('jobno');
     jobapp.stage__c = System.currentPageReference().getParameters().get('stage');
     jobapp.City__c= System.currentPageReference().getParameters().get('city');   
    }
   }