objects/Policyline__c.object
<CustomObject>
    <fields>
        <fullName>PolicyType__c</fullName>
        <label>policy</label>
        <referenceTo>tfe_policy__c</referenceTo>
        <relationshipLabel>Policylines</relationshipLabel>
        <relationshipName>Policylines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Policyline</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Policyline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policylines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tfe_policy__c.object
<CustomObject>
    <label>policy</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Policy Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/policy.cls
public with sharing class policy {
    public tfe_policy__c policy {get;set;}
    public policyline__c policyline{get;set;}
    private ApexPages.StandardController std;
    public policy(ApexPages.StandardController controller) {
     std=controller;
    }
     public tfe_policy__C getpolicy()
    {
     return (tfe_policy__C) std.getRecord();
    }
    public boolean inser()
    {  
       boolean result=true;
       //tfe_policy__c pp= new tfe_policy__c();
       //pp= [select id from tfe_policy__c where name = :policy.name limit 1];
       policyline__c pol = new policyline__c();
       pol.Name  = policyline.Name;
       pol.PolicyType__c = getpolicy().id;
      insert pol;
      return result;
    }

}