objects/Serviceappointments__c.object
<CustomObject>
    <label>Service Appointments</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Serviceappointments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Workorder__c.object
<CustomObject>
    <fields>
        <fullName>Cases__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>workorders</relationshipLabel>
        <relationshipName>workorders</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Serviceappointments__c</fullName>
        <label>Service Appointments</label>
        <referenceTo>Serviceappointments__c</referenceTo>
        <relationshipLabel>workorders</relationshipLabel>
        <relationshipName>workorders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workorder</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Workorders Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>workorders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/amartest.cls
public class amartest {
    public  void getuser(){
        list<case> cases =[select id,CaseNumber,(select Serviceappointments__r.Name,Serviceappointments__r.owner.id 
                                                 from workorders__r where Serviceappointments__r.owner.id = :userinfo.getUserId() ) 
                           from case  ];
        list<case> newcases = new list<case>();
        for (case c: cases)
        {    
          // System.debug('Case Number ' + c.CaseNumber);      
    	   if(c.workorders__r != null && c.workorders__r.size() > 0){
              newcases.add(c);
            }
        }
        
        for(case c:newcases)
          System.debug('Case Number ' + c.CaseNumber);  
        
    }
}